### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by Guneetsinghtuli** [chingu-voyages/ChinguResourceList#34]
There are few things that can be improved in the Readme and I would like to work on them

1. Adding Resources for JS Frameworks like `Angular` and `Vue, and For `MongoDB` as well
2. I would prefer that to have `React` resources in the Library Section as its a JS Library and not a framework
3. The link to Package and Communication in Content doesn't work 
4. Remove some Lint error
5. It will also be great to link some video resources as well

**Comment by jdmedlock** [comment]
Thanks for these suggestions @Guneetsinghtuli. 
Approved - 1,3,4,5

I'd like to keep `React` in the Framework section so that when we group `Angular`, `Vue`, etc. all together. React and Vue are libraries, but Angular is a true framework so if we move these to Libraries, technically Angular will be in the wrong spot :) . I'm open to other suggestions though.
